name = "Magic Box"
description = "A simple blog theme with project landing-pages"
license = "MIT"
homepage = "https://github.com/dulvui/magic-box"
min_version = "0.4.0"
demo = "https://simondalvai.org"

[extra]

[author]
name = "Simon Dalvai"
homepage = "https://simondalvai.org"
